sudo: required

before_install:
- git clone --depth 1 https://github.com/KiCad/kicad-library-utils /home/travis/build/kicad-library-utils
- git clone --depth 1 https://github.com/KiCad/kicad-library /home/travis/build/kicad-library-old

script:
- sudo bash /home/travis/build/kicad-library-old/library-check.sh $TRAVIS_BUILD_DIR
