M48
; DRILL file {KiCad 7.0.6-0} date 2023 October 19, Thursday 14:17:20
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-19T14:17:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.1614Y-2.3232
X4.1614Y-2.5508
T2
X4.1417Y-2.872
X4.1417Y-3.187
T0
M30
